// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.20.3
// source: cognicore.proto

package cognicore

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 文本块（你发送给 Go 的数据）
type TextChunk struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ChunkId         string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`                                  // 当前 chunk 的唯一 ID（可选，如果 Go 不需要可以不传）
	FileId          string                 `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`                                     // 文件 ID（必需，标识这是哪个文件的 chunk）
	Chapter         string                 `protobuf:"bytes,3,opt,name=chapter,proto3" json:"chapter,omitempty"`                                                 // 章节标题
	ChapterNum      string                 `protobuf:"bytes,4,opt,name=chapter_num,json=chapterNum,proto3" json:"chapter_num,omitempty"`                         // 章节号（例如 "1.2", "3.2.1"）
	ChunkText       string                 `protobuf:"bytes,5,opt,name=chunk_text,json=chunkText,proto3" json:"chunk_text,omitempty"`                            // 文本内容
	EmbeddingVector []float32              `protobuf:"fixed32,6,rep,packed,name=embedding_vector,json=embeddingVector,proto3" json:"embedding_vector,omitempty"` // 向量（float 数组，不是 string！）
	ChunkIndex      int32                  `protobuf:"varint,8,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`                        // 这是第几个 chunk（从 0 开始）
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TextChunk) Reset() {
	*x = TextChunk{}
	mi := &file_cognicore_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextChunk) ProtoMessage() {}

func (x *TextChunk) ProtoReflect() protoreflect.Message {
	mi := &file_cognicore_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextChunk.ProtoReflect.Descriptor instead.
func (*TextChunk) Descriptor() ([]byte, []int) {
	return file_cognicore_proto_rawDescGZIP(), []int{0}
}

func (x *TextChunk) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *TextChunk) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *TextChunk) GetChapter() string {
	if x != nil {
		return x.Chapter
	}
	return ""
}

func (x *TextChunk) GetChapterNum() string {
	if x != nil {
		return x.ChapterNum
	}
	return ""
}

func (x *TextChunk) GetChunkText() string {
	if x != nil {
		return x.ChunkText
	}
	return ""
}

func (x *TextChunk) GetEmbeddingVector() []float32 {
	if x != nil {
		return x.EmbeddingVector
	}
	return nil
}

func (x *TextChunk) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

// 文档元信息（在开始发送 chunks 之前先发这个）
type DocumentMetadata struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FileId          string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`                             // 文件 ID
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                             // 用户 ID
	Filename        string                 `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`                                       // 文件名
	TotalPages      int32                  `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`                // 总页数
	EstimatedChunks int32                  `protobuf:"varint,5,opt,name=estimated_chunks,json=estimatedChunks,proto3" json:"estimated_chunks,omitempty"` // 预计会发送多少个 chunks
	FileHash        string                 `protobuf:"bytes,6,opt,name=file_hash,json=fileHash,proto3" json:"file_hash,omitempty"`                       // 文件哈希（用于去重）
	FileSize        int64                  `protobuf:"varint,7,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`                      // 文件大小（字节）
	CreatedAt       string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                    // 处理时间
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DocumentMetadata) Reset() {
	*x = DocumentMetadata{}
	mi := &file_cognicore_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentMetadata) ProtoMessage() {}

func (x *DocumentMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_cognicore_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentMetadata.ProtoReflect.Descriptor instead.
func (*DocumentMetadata) Descriptor() ([]byte, []int) {
	return file_cognicore_proto_rawDescGZIP(), []int{1}
}

func (x *DocumentMetadata) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *DocumentMetadata) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DocumentMetadata) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *DocumentMetadata) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *DocumentMetadata) GetEstimatedChunks() int32 {
	if x != nil {
		return x.EstimatedChunks
	}
	return 0
}

func (x *DocumentMetadata) GetFileHash() string {
	if x != nil {
		return x.FileHash
	}
	return ""
}

func (x *DocumentMetadata) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *DocumentMetadata) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// 流式请求（可以是元信息或 chunk）
type IngestRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to RequestType:
	//
	//	*IngestRequest_Metadata
	//	*IngestRequest_Chunk
	RequestType   isIngestRequest_RequestType `protobuf_oneof:"request_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestRequest) Reset() {
	*x = IngestRequest{}
	mi := &file_cognicore_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestRequest) ProtoMessage() {}

func (x *IngestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cognicore_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestRequest.ProtoReflect.Descriptor instead.
func (*IngestRequest) Descriptor() ([]byte, []int) {
	return file_cognicore_proto_rawDescGZIP(), []int{2}
}

func (x *IngestRequest) GetRequestType() isIngestRequest_RequestType {
	if x != nil {
		return x.RequestType
	}
	return nil
}

func (x *IngestRequest) GetMetadata() *DocumentMetadata {
	if x != nil {
		if x, ok := x.RequestType.(*IngestRequest_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *IngestRequest) GetChunk() *TextChunk {
	if x != nil {
		if x, ok := x.RequestType.(*IngestRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isIngestRequest_RequestType interface {
	isIngestRequest_RequestType()
}

type IngestRequest_Metadata struct {
	Metadata *DocumentMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"` // 第一条消息：元信息
}

type IngestRequest_Chunk struct {
	Chunk *TextChunk `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"` // 后续消息：文本块
}

func (*IngestRequest_Metadata) isIngestRequest_RequestType() {}

func (*IngestRequest_Chunk) isIngestRequest_RequestType() {}

// Go backend 的 ACK 响应
type IngestResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 消息（成功/失败原因）
	// 统计信息
	ChunksReceived int32 `protobuf:"varint,3,opt,name=chunks_received,json=chunksReceived,proto3" json:"chunks_received,omitempty"` // 收到了多少个 chunks
	ChunksStored   int32 `protobuf:"varint,4,opt,name=chunks_stored,json=chunksStored,proto3" json:"chunks_stored,omitempty"`       // 成功存储了多少个
	ChunksFailed   int32 `protobuf:"varint,5,opt,name=chunks_failed,json=chunksFailed,proto3" json:"chunks_failed,omitempty"`       // 失败了多少个
	// 处理时间（毫秒）
	ProcessingTimeMs int64 `protobuf:"varint,7,opt,name=processing_time_ms,json=processingTimeMs,proto3" json:"processing_time_ms,omitempty"`
	// 文件 ID 用于确认
	FileId        string `protobuf:"bytes,8,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestResponse) Reset() {
	*x = IngestResponse{}
	mi := &file_cognicore_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestResponse) ProtoMessage() {}

func (x *IngestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cognicore_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestResponse.ProtoReflect.Descriptor instead.
func (*IngestResponse) Descriptor() ([]byte, []int) {
	return file_cognicore_proto_rawDescGZIP(), []int{3}
}

func (x *IngestResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *IngestResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *IngestResponse) GetChunksReceived() int32 {
	if x != nil {
		return x.ChunksReceived
	}
	return 0
}

func (x *IngestResponse) GetChunksStored() int32 {
	if x != nil {
		return x.ChunksStored
	}
	return 0
}

func (x *IngestResponse) GetChunksFailed() int32 {
	if x != nil {
		return x.ChunksFailed
	}
	return 0
}

func (x *IngestResponse) GetProcessingTimeMs() int64 {
	if x != nil {
		return x.ProcessingTimeMs
	}
	return 0
}

func (x *IngestResponse) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

// Embedding 请求（Go 调用 Python 时使用）
type EmbeddingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"` // 任务 ID（用于日志追踪）
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`                   // 要向量化的文本
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbeddingRequest) Reset() {
	*x = EmbeddingRequest{}
	mi := &file_cognicore_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingRequest) ProtoMessage() {}

func (x *EmbeddingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cognicore_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingRequest.ProtoReflect.Descriptor instead.
func (*EmbeddingRequest) Descriptor() ([]byte, []int) {
	return file_cognicore_proto_rawDescGZIP(), []int{4}
}

func (x *EmbeddingRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *EmbeddingRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// Embedding 响应
type EmbeddingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Embeddings    []float32              `protobuf:"fixed32,3,rep,packed,name=embeddings,proto3" json:"embeddings,omitempty"` // 向量结果（float 数组）
	Dimension     int32                  `protobuf:"varint,4,opt,name=dimension,proto3" json:"dimension,omitempty"`           // 向量维度
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbeddingResponse) Reset() {
	*x = EmbeddingResponse{}
	mi := &file_cognicore_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingResponse) ProtoMessage() {}

func (x *EmbeddingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cognicore_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingResponse.ProtoReflect.Descriptor instead.
func (*EmbeddingResponse) Descriptor() ([]byte, []int) {
	return file_cognicore_proto_rawDescGZIP(), []int{5}
}

func (x *EmbeddingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EmbeddingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EmbeddingResponse) GetEmbeddings() []float32 {
	if x != nil {
		return x.Embeddings
	}
	return nil
}

func (x *EmbeddingResponse) GetDimension() int32 {
	if x != nil {
		return x.Dimension
	}
	return 0
}

var File_cognicore_proto protoreflect.FileDescriptor

const file_cognicore_proto_rawDesc = "" +
	"\n" +
	"\x0fcognicore.proto\x12\tcognicore\"\xe5\x01\n" +
	"\tTextChunk\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\tR\x06fileId\x12\x18\n" +
	"\achapter\x18\x03 \x01(\tR\achapter\x12\x1f\n" +
	"\vchapter_num\x18\x04 \x01(\tR\n" +
	"chapterNum\x12\x1d\n" +
	"\n" +
	"chunk_text\x18\x05 \x01(\tR\tchunkText\x12)\n" +
	"\x10embedding_vector\x18\x06 \x03(\x02R\x0fembeddingVector\x12\x1f\n" +
	"\vchunk_index\x18\b \x01(\x05R\n" +
	"chunkIndex\"\x85\x02\n" +
	"\x10DocumentMetadata\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\x05R\n" +
	"totalPages\x12)\n" +
	"\x10estimated_chunks\x18\x05 \x01(\x05R\x0festimatedChunks\x12\x1b\n" +
	"\tfile_hash\x18\x06 \x01(\tR\bfileHash\x12\x1b\n" +
	"\tfile_size\x18\a \x01(\x03R\bfileSize\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\"\x88\x01\n" +
	"\rIngestRequest\x129\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1b.cognicore.DocumentMetadataH\x00R\bmetadata\x12,\n" +
	"\x05chunk\x18\x02 \x01(\v2\x14.cognicore.TextChunkH\x00R\x05chunkB\x0e\n" +
	"\frequest_type\"\xfe\x01\n" +
	"\x0eIngestResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12'\n" +
	"\x0fchunks_received\x18\x03 \x01(\x05R\x0echunksReceived\x12#\n" +
	"\rchunks_stored\x18\x04 \x01(\x05R\fchunksStored\x12#\n" +
	"\rchunks_failed\x18\x05 \x01(\x05R\fchunksFailed\x12,\n" +
	"\x12processing_time_ms\x18\a \x01(\x03R\x10processingTimeMs\x12\x17\n" +
	"\afile_id\x18\b \x01(\tR\x06fileId\"?\n" +
	"\x10EmbeddingRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"\x85\x01\n" +
	"\x11EmbeddingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1e\n" +
	"\n" +
	"embeddings\x18\x03 \x03(\x02R\n" +
	"embeddings\x12\x1c\n" +
	"\tdimension\x18\x04 \x01(\x05R\tdimension2\x9e\x01\n" +
	"\rIngestService\x12G\n" +
	"\x0eIngestDocument\x12\x18.cognicore.IngestRequest\x1a\x19.cognicore.IngestResponse(\x01\x12D\n" +
	"\x11IngestSingleChunk\x12\x14.cognicore.TextChunk\x1a\x19.cognicore.IngestResponse2]\n" +
	"\x10EmbeddingService\x12I\n" +
	"\fGetEmbedding\x12\x1b.cognicore.EmbeddingRequest\x1a\x1c.cognicore.EmbeddingResponseB>Z<github.com/ZZZiggy_/go_chat_backend/platform/proto/cognicoreb\x06proto3"

var (
	file_cognicore_proto_rawDescOnce sync.Once
	file_cognicore_proto_rawDescData []byte
)

func file_cognicore_proto_rawDescGZIP() []byte {
	file_cognicore_proto_rawDescOnce.Do(func() {
		file_cognicore_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cognicore_proto_rawDesc), len(file_cognicore_proto_rawDesc)))
	})
	return file_cognicore_proto_rawDescData
}

var file_cognicore_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_cognicore_proto_goTypes = []any{
	(*TextChunk)(nil),         // 0: cognicore.TextChunk
	(*DocumentMetadata)(nil),  // 1: cognicore.DocumentMetadata
	(*IngestRequest)(nil),     // 2: cognicore.IngestRequest
	(*IngestResponse)(nil),    // 3: cognicore.IngestResponse
	(*EmbeddingRequest)(nil),  // 4: cognicore.EmbeddingRequest
	(*EmbeddingResponse)(nil), // 5: cognicore.EmbeddingResponse
}
var file_cognicore_proto_depIdxs = []int32{
	1, // 0: cognicore.IngestRequest.metadata:type_name -> cognicore.DocumentMetadata
	0, // 1: cognicore.IngestRequest.chunk:type_name -> cognicore.TextChunk
	2, // 2: cognicore.IngestService.IngestDocument:input_type -> cognicore.IngestRequest
	0, // 3: cognicore.IngestService.IngestSingleChunk:input_type -> cognicore.TextChunk
	4, // 4: cognicore.EmbeddingService.GetEmbedding:input_type -> cognicore.EmbeddingRequest
	3, // 5: cognicore.IngestService.IngestDocument:output_type -> cognicore.IngestResponse
	3, // 6: cognicore.IngestService.IngestSingleChunk:output_type -> cognicore.IngestResponse
	5, // 7: cognicore.EmbeddingService.GetEmbedding:output_type -> cognicore.EmbeddingResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_cognicore_proto_init() }
func file_cognicore_proto_init() {
	if File_cognicore_proto != nil {
		return
	}
	file_cognicore_proto_msgTypes[2].OneofWrappers = []any{
		(*IngestRequest_Metadata)(nil),
		(*IngestRequest_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cognicore_proto_rawDesc), len(file_cognicore_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_cognicore_proto_goTypes,
		DependencyIndexes: file_cognicore_proto_depIdxs,
		MessageInfos:      file_cognicore_proto_msgTypes,
	}.Build()
	File_cognicore_proto = out.File
	file_cognicore_proto_goTypes = nil
	file_cognicore_proto_depIdxs = nil
}
