# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import cognicore_pb2 as cognicore__pb2

GRPC_GENERATED_VERSION = '1.69.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in cognicore_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IngestServiceStub(object):
    """数据导入服务
    角色分配：
    - Go：服务端（Server），实现这个服务，监听端口，等待 Python 连接
    - Python：客户端（Client），连接 Go，调用这个服务，发送数据
    数据流向：Python → Go
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IngestDocument = channel.stream_unary(
                '/cognicore.IngestService/IngestDocument',
                request_serializer=cognicore__pb2.IngestRequest.SerializeToString,
                response_deserializer=cognicore__pb2.IngestResponse.FromString,
                _registered_method=True)
        self.IngestSingleChunk = channel.unary_unary(
                '/cognicore.IngestService/IngestSingleChunk',
                request_serializer=cognicore__pb2.TextChunk.SerializeToString,
                response_deserializer=cognicore__pb2.IngestResponse.FromString,
                _registered_method=True)


class IngestServiceServicer(object):
    """数据导入服务
    角色分配：
    - Go：服务端（Server），实现这个服务，监听端口，等待 Python 连接
    - Python：客户端（Client），连接 Go，调用这个服务，发送数据
    数据流向：Python → Go
    """

    def IngestDocument(self, request_iterator, context):
        """Client Streaming: Python 持续发送文档数据，Go 最后返回一次 ACK
        使用场景：处理整个 PDF，发送 metadata + 所有 chunks
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IngestSingleChunk(self, request, context):
        """Unary 模式：单个 chunk 上传
        使用场景：重试失败的 chunk，或者测试单个 chunk
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IngestServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IngestDocument': grpc.stream_unary_rpc_method_handler(
                    servicer.IngestDocument,
                    request_deserializer=cognicore__pb2.IngestRequest.FromString,
                    response_serializer=cognicore__pb2.IngestResponse.SerializeToString,
            ),
            'IngestSingleChunk': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestSingleChunk,
                    request_deserializer=cognicore__pb2.TextChunk.FromString,
                    response_serializer=cognicore__pb2.IngestResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cognicore.IngestService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cognicore.IngestService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IngestService(object):
    """数据导入服务
    角色分配：
    - Go：服务端（Server），实现这个服务，监听端口，等待 Python 连接
    - Python：客户端（Client），连接 Go，调用这个服务，发送数据
    数据流向：Python → Go
    """

    @staticmethod
    def IngestDocument(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/cognicore.IngestService/IngestDocument',
            cognicore__pb2.IngestRequest.SerializeToString,
            cognicore__pb2.IngestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IngestSingleChunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cognicore.IngestService/IngestSingleChunk',
            cognicore__pb2.TextChunk.SerializeToString,
            cognicore__pb2.IngestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class APIKeyServiceStub(object):
    """API Key 传递
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProvideAPIKey = channel.unary_unary(
                '/cognicore.APIKeyService/ProvideAPIKey',
                request_serializer=cognicore__pb2.APIKeyRequest.SerializeToString,
                response_deserializer=cognicore__pb2.APIKeyResponse.FromString,
                _registered_method=True)


class APIKeyServiceServicer(object):
    """API Key 传递
    """

    def ProvideAPIKey(self, request, context):
        """Go 调用 Python：传递 API Key
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_APIKeyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProvideAPIKey': grpc.unary_unary_rpc_method_handler(
                    servicer.ProvideAPIKey,
                    request_deserializer=cognicore__pb2.APIKeyRequest.FromString,
                    response_serializer=cognicore__pb2.APIKeyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cognicore.APIKeyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cognicore.APIKeyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class APIKeyService(object):
    """API Key 传递
    """

    @staticmethod
    def ProvideAPIKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cognicore.APIKeyService/ProvideAPIKey',
            cognicore__pb2.APIKeyRequest.SerializeToString,
            cognicore__pb2.APIKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class EmbeddingServiceStub(object):
    """Embedding 服务
    角色分配：
    - Python：服务端（Server），实现这个服务，监听端口，等待 Go 连接
    - Go：客户端（Client），连接 Python，调用这个服务，发送文本进行向量化
    数据流向：Go → Python → Go
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetEmbedding = channel.unary_unary(
                '/cognicore.EmbeddingService/GetEmbedding',
                request_serializer=cognicore__pb2.EmbeddingRequest.SerializeToString,
                response_deserializer=cognicore__pb2.EmbeddingResponse.FromString,
                _registered_method=True)


class EmbeddingServiceServicer(object):
    """Embedding 服务
    角色分配：
    - Python：服务端（Server），实现这个服务，监听端口，等待 Go 连接
    - Go：客户端（Client），连接 Python，调用这个服务，发送文本进行向量化
    数据流向：Go → Python → Go
    """

    def GetEmbedding(self, request, context):
        """Go 调用 Python：发送文本，获取向量
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EmbeddingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetEmbedding': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEmbedding,
                    request_deserializer=cognicore__pb2.EmbeddingRequest.FromString,
                    response_serializer=cognicore__pb2.EmbeddingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cognicore.EmbeddingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cognicore.EmbeddingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EmbeddingService(object):
    """Embedding 服务
    角色分配：
    - Python：服务端（Server），实现这个服务，监听端口，等待 Go 连接
    - Go：客户端（Client），连接 Python，调用这个服务，发送文本进行向量化
    数据流向：Go → Python → Go
    """

    @staticmethod
    def GetEmbedding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cognicore.EmbeddingService/GetEmbedding',
            cognicore__pb2.EmbeddingRequest.SerializeToString,
            cognicore__pb2.EmbeddingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
