# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cognicore.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'cognicore.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63ognicore.proto\x12\tcognicore\"\x97\x01\n\tTextChunk\x12\x10\n\x08\x63hunk_id\x18\x01 \x01(\t\x12\x0f\n\x07\x66ile_id\x18\x02 \x01(\t\x12\x0f\n\x07\x63hapter\x18\x03 \x01(\t\x12\x13\n\x0b\x63hapter_num\x18\x04 \x01(\t\x12\x12\n\nchunk_text\x18\x05 \x01(\t\x12\x18\n\x10\x65mbedding_vector\x18\x06 \x03(\x02\x12\x13\n\x0b\x63hunk_index\x18\x08 \x01(\x05\"\xaf\x01\n\x10\x44ocumentMetadata\x12\x0f\n\x07\x66ile_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x10\n\x08\x66ilename\x18\x03 \x01(\t\x12\x13\n\x0btotal_pages\x18\x04 \x01(\x05\x12\x18\n\x10\x65stimated_chunks\x18\x05 \x01(\x05\x12\x11\n\tfile_hash\x18\x06 \x01(\t\x12\x11\n\tfile_size\x18\x07 \x01(\x03\x12\x12\n\ncreated_at\x18\x08 \x01(\t\"w\n\rIngestRequest\x12/\n\x08metadata\x18\x01 \x01(\x0b\x32\x1b.cognicore.DocumentMetadataH\x00\x12%\n\x05\x63hunk\x18\x02 \x01(\x0b\x32\x14.cognicore.TextChunkH\x00\x42\x0e\n\x0crequest_type\"\xa6\x01\n\x0eIngestResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x17\n\x0f\x63hunks_received\x18\x03 \x01(\x05\x12\x15\n\rchunks_stored\x18\x04 \x01(\x05\x12\x15\n\rchunks_failed\x18\x05 \x01(\x05\x12\x1a\n\x12processing_time_ms\x18\x07 \x01(\x03\x12\x0f\n\x07\x66ile_id\x18\x08 \x01(\t\"1\n\x10\x45mbeddingRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\"\\\n\x11\x45mbeddingResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x12\n\nembeddings\x18\x03 \x03(\x02\x12\x11\n\tdimension\x18\x04 \x01(\x05\x32\x9e\x01\n\rIngestService\x12G\n\x0eIngestDocument\x12\x18.cognicore.IngestRequest\x1a\x19.cognicore.IngestResponse(\x01\x12\x44\n\x11IngestSingleChunk\x12\x14.cognicore.TextChunk\x1a\x19.cognicore.IngestResponse2]\n\x10\x45mbeddingService\x12I\n\x0cGetEmbedding\x12\x1b.cognicore.EmbeddingRequest\x1a\x1c.cognicore.EmbeddingResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cognicore_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TEXTCHUNK']._serialized_start=31
  _globals['_TEXTCHUNK']._serialized_end=182
  _globals['_DOCUMENTMETADATA']._serialized_start=185
  _globals['_DOCUMENTMETADATA']._serialized_end=360
  _globals['_INGESTREQUEST']._serialized_start=362
  _globals['_INGESTREQUEST']._serialized_end=481
  _globals['_INGESTRESPONSE']._serialized_start=484
  _globals['_INGESTRESPONSE']._serialized_end=650
  _globals['_EMBEDDINGREQUEST']._serialized_start=652
  _globals['_EMBEDDINGREQUEST']._serialized_end=701
  _globals['_EMBEDDINGRESPONSE']._serialized_start=703
  _globals['_EMBEDDINGRESPONSE']._serialized_end=795
  _globals['_INGESTSERVICE']._serialized_start=798
  _globals['_INGESTSERVICE']._serialized_end=956
  _globals['_EMBEDDINGSERVICE']._serialized_start=958
  _globals['_EMBEDDINGSERVICE']._serialized_end=1051
# @@protoc_insertion_point(module_scope)
